// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmHhd36Fy_WVJ-eyjyUpBXHE_RTFeat3g',
    appId: '1:1027669293172:android:390d028b9c048eda353921',
    messagingSenderId: '1027669293172',
    projectId: 'fir-phoneauth-3516d',
    storageBucket: 'fir-phoneauth-3516d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_1nJC6IL9cnVT3NaNp3-g3dii5MX0Ao',
    appId: '1:1027669293172:ios:9c653f4f12f1ab6b353921',
    messagingSenderId: '1027669293172',
    projectId: 'fir-phoneauth-3516d',
    storageBucket: 'fir-phoneauth-3516d.appspot.com',
    androidClientId: '1027669293172-itbkam64t16p3ehf98ofqicnks1mfh51.apps.googleusercontent.com',
    iosClientId: '1027669293172-gk3a7i8mp6tu8ivvi27gdrlf8dflglkn.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthTut',
  );
}
